
using Microsoft.AspNetCore.HttpLogging;
using Microsoft.AspNetCore.Identity;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.AddHttpLogging(
    opts => opts.LoggingFields = HttpLoggingFields.RequestProperties);

// Ensure logs generated by HttpLoggingMiddleware are written to the console.
// Ensure logs of severity Information or higher created in the Microsoft.AspNetCore.HttpLogging category will be included in the log output.
builder.Logging.AddFilter("Microsoft.AspNetCore.HttpLogging", LogLevel.Information);

// cant register any more services or change your logging configuration after this line
WebApplication app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseHttpLogging();
}

app.MapGet("/", () => "Hello World!");
app.MapGet("/person", () => new Person("Sun", "James"));

app.Run();

public record Person(string FirstName, string lastName);